<a href="https://colab.research.google.com/github/Yeury-DCM/EmployeesIncomeCalculator/blob/master/Inferencia_De_Ingresos_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Recopilación de 5 Nóminas

Importación librerías necearias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Importación de Datasets crudos

In [37]:
#Se va omitir las primeras filas del documento para que lea desde que empiezan los cabezales de la columna en adelante

cassd_df = pd.read_excel('CASSD.xlsx', skiprows = 5)
edesur_df = pd.read_excel('EDESUR.xlsx', skiprows = 6)
indrhi_df = pd.read_excel('INDRHI.xlsx', skiprows = 19)
minerd_df = pd.read_excel('MINERD.xlsx', skiprows = 7)
uasd_df = pd.read_excel('UASD.xlsx', skiprows = 8)

/usr/local/lib/python3.10/dist-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

,NO.,SEXO,Nombre_apellido,Departamento,Funcion_o_puesto,Estado,Desde,Sueldo_bruto,Otros_ingresos,Total_ingresos,ISR,AFP,SFS,Otros_descuentos,Total_descuentos,Total_neto
0,1,M,Jose Horacio Cabrera Tejada,RECTORIA,DIRECTOR GRAL DE TECNOLOGIA DE LA INFORMACION,DE CARRERA,1975-08-01,195857.70,48798.22,244655.92,31822.98,5250.77,4742.4,59416.92,101233.07,143422.85
1,2,F,ISABEL MARIA ULLOA PAYAMPS,DEPARTAMENTO DE PERSONAL ADMINISTRATIVO,Director de Recursos Humanos,DE CARRERA,1998-02-09,172759.43,75135.51,247894.94,29347.58,4958.20,4742.4,9331.00,48379.18,199515.76
2,3,F,Adela Jocelyn Rosario Gutierrez,RECTORIA,Asistente Ejecutivo Rectoria,DE CARRERA,1993-02-22,167706.65,74922.72,242629.37,28120.63,4813.18,4742.4,118487.72,156163.93,86465.44
3,4,M,Franklin Alberto Beltre Fernandez,DEPARTAMENTO DE TECNOLOGIA,Director Departamento Tecnologia,DE CARRERA,2006-11-01,162141.25,70319.00,232460.25,26769.22,4653.45,4742.4,84420.02,120585.09,111875.16
4,5,F,Nadesha M Paniagua M,DEPARTAMENTO DE COMPRA DE CONTRATACIONES DE BI...,Director de Compras,DE CARRERA,1999-04-19,159183.68,69233.01,228416.69,26051.04,4568.57,4742.4,83950.15,119312.16,109104.53

## Procesar, Homogenizar y Limpiar la Data